language: java
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: "build & test"
      name: "Test if generated code matches templates"
      script:
        - mkdir tmp
        - cd primitivepower-generator
        - mvn -B -V install -DskipTests
        - mvn -B -V test
        - mvn exec:java -DskipTests -Dexec.args="../tmp/"
        - cd ..
        - diff -qrN -x '*.class' tmp/ primitivepower/
    - name: "Tests"
      install:
        - cd primitivepower
        - mvn -B -V install -DskipTests
      script:
        - mvn -B -V test


#remove the installed maven jars before caching
before_cache:
  - rm -f -r $HOME/.m2/repository/com/github/power-libraries
cache:
  directories:
    - "$HOME/.m2"