language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
jobs:
  include:
    - stage: "build & test"
      name: "test if generated code matches templates"
      script: >
        mkdir tmp &&
        cd primitivepower-generator &&
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V &&
        mvn test verify -P test-coverage -Dmaven.javadoc.skip=true -B &&
        mvn exec:java -DskipTests=true -Dmaven.javadoc.skip=true -Dexec.args="../tmp/" &&
        cd .. &&
        diff -qrN -x '*.class' tmp/ primitivepower/ &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-generator/target/site/jacoco/jacoco.xml --partial
    - script: >
        cd primitivepower &&
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V &&
        mvn test verify -P test-coverage -Dmaven.javadoc.skip=true -B &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-boolean/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-byte/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-char/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-double/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-float/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-int/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-long/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-object/target/site/jacoco/jacoco.xml --partial &&
        java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r primitivepower-short/target/site/jacoco/jacoco.xml --partial
      name: "test generated code"
    - stage: "finish coverage report"
      script: java -jar ~/codacy-coverage-reporter-assembly-latest.jar final
