language: java
jdk:
  - oraclejdk8
  - oraclejdk9
addons:
  sonarcloud:
    organization: "power-libraries"
after_success: mvn exec:java -DskipTests=true -Dmaven.javadoc.skip=true && sonar-scanner && cd target/primitivepower/ && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && mvn test -Dmaven.javadoc.skip=true -B