pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    cd primitivepower-generator
    mvn -B -V install -DskipTests
    mvn -B -V test
    mvn -B -V exec:java -DskipTests -Dexec.args="../primitivepower/"
    cd ..
    git add *
    git diff --quiet HEAD || \
    {
      git config user.email "50981256+power-libraries-bot@users.noreply.github.com"
      git config user.name "power-libraries-bot"
      git commit --message "regenerated derived code"
      git push origin HEAD:$(Build.SourceBranch)
      exit -1
    }
  displayName: regenerate code

- task: Maven@3
  displayName: tests
  inputs:
    mavenPomFile: 'primitivepower/pom.xml'
    goals: test verify
    options: -B -T 1C -P test-coverage
    jdkVersionOption: '1.8'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- bash: bash <(curl -s https://codecov.io/bash)
  displayName: upload coverage
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)
